apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: database
data:
  redis.conf: |
    # Redis Configuration
    requirepass admin
    masterauth admin
    bind 0.0.0.0
    port 6379
    dir /data
    appendonly yes